"""
Exporter module for the slideia package.
"""

import json
import os
import sys

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt
from slideia.core.logging import get_logger
from slideia.domain.deck.services import create_minimal_template

logger = get_logger(__name__)


def export_slides(input_path: str, output_path: str):
    """
    Export slides from a JSON file to a PowerPoint file.
    """
    if not os.path.exists(input_path):
        logger.error(f"Input file not found: {input_path}")
        raise FileNotFoundError(f"Input file not found: {input_path}")

    # Use the minimal professional template
    template_path = os.path.join(
        os.path.dirname(__file__), "templates", "base_template.pptx"
    )
    if not os.path.exists(template_path):
        logger.warning(
            f"Template not found: {template_path}, generating minimal template"
        )
        out_path = os.path.join(
            os.path.dirname(__file__), "templates", "base_template.pptx"
        )
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        create_minimal_template(out_path)
        logger.info(f"Template saved to {out_path}")

    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    prs = Presentation(template_path)

    # Remove all slides from the template to avoid duplicates in output
    while len(prs.slides) > 0:
        rId = prs.slides._sldIdLst[0].rId
        prs.part.drop_rel(rId)
        del prs.slides._sldIdLst[0]

    # Title slide (use first layout)
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = data.get("title", "Untitled Presentation")
    if len(slide.placeholders) > 1:
        subtitle = data.get("subtitle", "Generated by slideia exporter")
        slide.placeholders[1].text = subtitle

    # Content slides - Use BLANK layout
    blank_layout = None
    for layout in prs.slide_layouts:
        if len(layout.placeholders) == 0 or "blank" in layout.name.lower():
            blank_layout = layout
            logger.info(f"Found blank layout: {layout.name}")
            break

    if blank_layout is None:
        try:
            blank_layout = prs.slide_layouts[6]
            logger.info("Using layout 6 as blank")
        except IndexError:
            blank_layout = prs.slide_layouts[1]
            logger.warning("Using layout 1, blank not found")

    for slide_index, s in enumerate(data.get("slides", [])):
        logger.info(f"Processing slide {slide_index + 1}")

        content_slide = prs.slides.add_slide(blank_layout)

        # Get theme settings - HANDLE TYPE MISMATCHES
        theme = s.get("theme", {})
        if not isinstance(theme, dict):
            logger.warning(f"Theme is {type(theme)}, expected dict. Using empty dict.")
            theme = {}

        font_name = theme.get("font", "Calibri")
        if not isinstance(font_name, str):
            logger.warning(f"Font is {type(font_name)}, expected str. Using 'Calibri'.")
            font_name = "Calibri"

        # Parse color if provided
        font_color = None
        if "color" in theme:
            color_value = theme["color"]
            if isinstance(color_value, str):
                try:
                    rgb = color_value.lstrip("#")
                    font_color = RGBColor(
                        int(rgb[0:2], 16), int(rgb[2:4], 16), int(rgb[4:6], 16)
                    )
                except Exception as e:
                    logger.warning(f"Color parsing failed: {e}")
            else:
                logger.warning(f"Color is {type(color_value)}, expected str")

        # Get title - SAFE EXTRACTION
        title_text = s.get("title", f"Slide {slide_index + 1}")
        if not isinstance(title_text, str):
            logger.warning(f"Title is {type(title_text)}, converting to str")
            title_text = str(title_text)

        # Add title as a text box at the top
        title_left = Inches(0.5)
        title_top = Inches(0.5)
        title_width = Inches(9)
        title_height = Inches(0.8)

        title_box = content_slide.shapes.add_textbox(
            title_left, title_top, title_width, title_height
        )
        title_frame = title_box.text_frame
        title_frame.text = title_text
        title_frame.word_wrap = True

        # Style the title
        title_para = title_frame.paragraphs[0]
        title_para.font.size = Pt(32)
        title_para.font.bold = True
        title_para.font.name = font_name
        if font_color:
            title_para.font.color.rgb = font_color
        title_para.alignment = PP_ALIGN.LEFT

        # Add content text box below title
        content_left = Inches(0.5)
        content_top = Inches(1.5)
        content_width = Inches(6)
        content_height = Inches(5)

        content_box = content_slide.shapes.add_textbox(
            content_left, content_top, content_width, content_height
        )
        text_frame = content_box.text_frame
        text_frame.word_wrap = True
        text_frame.margin_left = Inches(0.1)
        text_frame.margin_right = Inches(0.1)
        text_frame.margin_top = Inches(0.1)
        text_frame.margin_bottom = Inches(0.1)

        # Get summary - SAFE EXTRACTION
        summary = s.get("summary", "")
        if not isinstance(summary, str):
            logger.warning(f"Summary is {type(summary)}, converting to str")
            summary = str(summary) if summary else ""
        summary = summary.strip()

        # Add summary if present
        if summary:
            summary_lines = summary.split("\n")
            for i, line in enumerate(summary_lines):
                if i == 0:
                    p = text_frame.paragraphs[0]
                    p.text = line.strip()
                else:
                    p = text_frame.add_paragraph()
                    p.text = line.strip()

            p.level = 0
            p.font.size = Pt(14)
            p.font.name = font_name
            if font_color:
                p.font.color.rgb = font_color
            p.space_after = Pt(12) if i == len(summary_lines) - 1 else Pt(0)
            p.alignment = PP_ALIGN.LEFT

        # Get bullets - SAFE EXTRACTION
        bullets = s.get("bullets", [])
        if not isinstance(bullets, list):
            logger.warning(
                f"Warning: bullets is {type(bullets)}, expected list. Converting.",
            )
            if isinstance(bullets, str):
                # If it's a string, split by newlines or use as single item
                bullets = [b.strip() for b in bullets.splitlines() if b.strip()]
            else:
                bullets = []

        # Add bullets
        for i, bullet_item in enumerate(bullets):
            # Ensure bullet is a string
            if not isinstance(bullet_item, str):
                logger.warning(
                    f"Warning: bullet {i} is {type(bullet_item)}, converting to str"
                )
                bullet_text = str(bullet_item)
            else:
                bullet_text = bullet_item

            # Create new paragraph for each bullet
            if i == 0 and not summary:
                p = text_frame.paragraphs[0]
            else:
                p = text_frame.add_paragraph()

            # Add bullet text
            clean_text = bullet_text.strip()
            if not clean_text.startswith("•") and not clean_text.startswith("-"):
                p.text = f"• {clean_text}"
            else:
                p.text = clean_text

            # Style bullet paragraph
            p.level = 0
            p.font.size = Pt(16)
            p.font.name = font_name
            if font_color:
                p.font.color.rgb = font_color
            p.space_after = Pt(8)
            p.alignment = PP_ALIGN.LEFT
            p.font.bold = False

        # Get notes - SAFE EXTRACTION
        notes = s.get("notes", "")
        if not isinstance(notes, str):
            logger.warning(
                f"Warning: notes is {type(notes)}, converting to str"
            )
            notes = str(notes) if notes else ""
        notes = notes.strip()

        # Add speaker notes if provided
        if notes:
            notes_slide = content_slide.notes_slide
            notes_frame = notes_slide.notes_text_frame
            notes_frame.text = notes

        # Get image prompt - SAFE EXTRACTION
        image_path = s.get("image_path")
        image_prompt = s.get("image_prompt", "")
        if not isinstance(image_prompt, str):
            logger.warning(
                f"Warning: image_prompt is {type(image_prompt)}, converting to str"
            )
            image_prompt = str(image_prompt) if image_prompt else ""
        image_prompt = image_prompt.strip()

        # Insert image on the right side
        if image_path and os.path.exists(image_path):
            try:
                left = Inches(7)
                top = Inches(1.5)
                width = Inches(2.5)
                pic = content_slide.shapes.add_picture(
                    image_path, left, top, width=width
                )

                if pic and image_prompt:
                    try:
                        if hasattr(pic, "alt_text"):
                            pic.alt_text = image_prompt
                    except Exception as e:
                        logger.warning(f"Alt text assignment failed: {e}")

            except Exception as e:
                logger.warning(f"Image insert failed: {e}. Using placeholder.")
                if image_prompt:
                    left = Inches(7)
                    top = Inches(1.5)
                    width = Inches(2.5)
                    height = Inches(2)
                    textbox = content_slide.shapes.add_textbox(left, top, width, height)
                    textbox_frame = textbox.text_frame
                    textbox_frame.text = f"[Image: {image_prompt}]"
                    textbox_frame.word_wrap = True
                    p = textbox_frame.paragraphs[0]
                    p.font.size = Pt(10)
                    p.font.italic = True
                    p.alignment = PP_ALIGN.CENTER

        elif image_prompt:
            left = Inches(7)
            top = Inches(1.5)
            width = Inches(2.5)
            height = Inches(2)
            textbox = content_slide.shapes.add_textbox(left, top, width, height)
            textbox_frame = textbox.text_frame
            textbox_frame.text = f"[Image: {image_prompt}]"
            textbox_frame.word_wrap = True
            p = textbox_frame.paragraphs[0]
            p.font.size = Pt(10)
            p.font.italic = True
            p.alignment = PP_ALIGN.CENTER

    prs.save(output_path)
    logger.info(f"Exported slides to {output_path}")
