"""
Exporter module for the slideia package.
"""

import json
import os
from io import BytesIO

import httpx
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.util import Inches, Pt
from slideia.core.logging import get_logger
from slideia.domain.deck.services import create_minimal_template

logger = get_logger(__name__)


async def export_slides(input_path: str, output_path: str):
    """
    Export slides from a JSON file to a PowerPoint file.
    """
    if not os.path.exists(input_path):
        logger.error(f"Input file not found: {input_path}")
        raise FileNotFoundError(f"Input file not found: {input_path}")

    # Use the minimal professional template
    template_path = os.path.join(os.path.dirname(__file__), "templates", "base_template.pptx")
    if not os.path.exists(template_path):
        logger.warning(f"Template not found: {template_path}, generating minimal template")
        out_path = os.path.join(os.path.dirname(__file__), "templates", "base_template.pptx")
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        create_minimal_template(out_path)
        logger.info(f"Template saved to {out_path}")

    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    prs = Presentation(template_path)

    # Remove all slides from the template to avoid duplicates in output
    while len(prs.slides) > 0:
        rId = prs.slides._sldIdLst[0].rId
        prs.part.drop_rel(rId)
        del prs.slides._sldIdLst[0]

    # Title slide (use first layout)
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = data.get("title", "Untitled Presentation")
    if not isinstance(title, str):
        logger.warning(f"Title is {type(title)}, converting to str for title slide")
        title = str(title)
    slide.shapes.title.text = title
    if len(slide.placeholders) > 1:
        subtitle = data.get("subtitle", "Generated by slideia exporter")
        if not isinstance(subtitle, str):
            logger.warning(f"Subtitle is {type(subtitle)}, converting to str for title slide")
            subtitle = str(subtitle)
        slide.placeholders[1].text = subtitle

    # Content slides - Use BLANK layout
    blank_layout = None
    for layout in prs.slide_layouts:
        if len(layout.placeholders) == 0 or "blank" in layout.name.lower():
            blank_layout = layout
            logger.info(f"Found blank layout: {layout.name}")
            break

    if blank_layout is None:
        try:
            blank_layout = prs.slide_layouts[6]
            logger.info("Using layout 6 as blank")
        except IndexError:
            blank_layout = prs.slide_layouts[1]
            logger.warning("Using layout 1, blank not found")

    for slide_index, s in enumerate(data.get("slides", [])):
        logger.info(f"Processing slide {slide_index + 1}")

        content_slide = prs.slides.add_slide(blank_layout)

        # Use slide-specific theme if present, otherwise fallback to global
        slide_theme = s.get("theme")
        if not isinstance(slide_theme, dict):
            slide_theme = {}

        global_font = data.get("font", "Calibri")
        global_palette = data.get("palette", [])

        # Set slide font
        # Priority: Slide Font -> Global Font -> Default
        font_name = slide_theme.get("font") or global_font or "Calibri"

        # Set slide colour
        # Priority: Slide Color -> Global Palette[0] -> Default (#000000)
        font_color = None
        color_hex = slide_theme.get("color")
        if not color_hex and global_palette:
            color_hex = global_palette[0]

        if color_hex:
            try:
                rgb = color_hex.lstrip("#")
                if len(rgb) == 6:
                    font_color = RGBColor(int(rgb[0:2], 16), int(rgb[2:4], 16), int(rgb[4:6], 16))
            except Exception as e:
                logger.warning(f"Color parsing failed for '{color_hex}': {e}")

        # Get title - SAFE EXTRACTION
        title_text = s.get("title", f"Slide {slide_index + 1}")
        if not isinstance(title_text, str):
            logger.warning(f"Title is {type(title_text)}, converting to str")
            title_text = str(title_text)

        # Add title as a text box at the top
        title_left = Inches(0.5)
        title_top = Inches(0.5)
        title_width = Inches(9)
        title_height = Inches(0.8)

        title_box = content_slide.shapes.add_textbox(title_left, title_top, title_width, title_height)
        title_frame = title_box.text_frame
        title_frame.text = title_text
        title_frame.word_wrap = True

        # Style the title
        title_para = title_frame.paragraphs[0]
        title_para.font.size = Pt(32)
        title_para.font.bold = True
        title_para.font.name = font_name
        if font_color:
            title_para.font.color.rgb = font_color
        title_para.alignment = PP_ALIGN.LEFT

        # Get slide layout (default to "bullets" for backward compatibility)
        layout = s.get("layout", "bullets")
        if not layout:
            layout = "bullets"

        # Determine if slide has an image (only bullets layout uses images)
        image_path = s.get("image_path")
        image_url = s.get("image_url")
        has_image = (bool(image_url) or bool(image_path)) and layout == "bullets"

        # Position and size the content text box dynamically to prevent overlap with the image slot
        if has_image:
            # Side-by-side layout: text content on the left
            content_left = Inches(0.8)
            content_top = Inches(1.8)
            content_width = Inches(5.5)
            content_height = Inches(4.5)
        else:
            # Full-width layout
            content_left = Inches(1.0)
            content_top = Inches(1.8)
            content_width = Inches(8.0)
            content_height = Inches(4.5)

        if layout in ("statement", "big_number"):
            content_top = Inches(2.2)
            content_height = Inches(3.5)

        content_box = content_slide.shapes.add_textbox(
            content_left, content_top, content_width, content_height
        )
        text_frame = content_box.text_frame
        text_frame.word_wrap = True
        text_frame.margin_left = Inches(0.1)
        text_frame.margin_right = Inches(0.1)
        text_frame.margin_top = Inches(0.1)
        text_frame.margin_bottom = Inches(0.1)

        # Center vertically for layout-specific text frames
        if layout in ("statement", "big_number"):
            text_frame.vertical_anchor = MSO_ANCHOR.MIDDLE

        # Get summary - SAFE EXTRACTION
        summary = s.get("summary", "")
        if not isinstance(summary, str):
            logger.warning(f"Summary is {type(summary)}, converting to str")
            summary = str(summary) if summary else ""
        summary = summary.strip()

        if layout == "bullets":
            has_summary_text = False
            # Add summary if present
            if summary:
                summary_lines = summary.split("\n")
                for i, line in enumerate(summary_lines):
                    if i == 0:
                        p = text_frame.paragraphs[0]
                        p.text = line.strip()
                    else:
                        p = text_frame.add_paragraph()
                        p.text = line.strip()

                p.level = 0
                p.font.size = Pt(14)
                p.font.name = font_name
                if font_color:
                    p.font.color.rgb = font_color
                p.space_after = Pt(12) if i == len(summary_lines) - 1 else Pt(0)
                p.alignment = PP_ALIGN.LEFT
                has_summary_text = True

            # Get bullets - SAFE EXTRACTION
            bullets = s.get("bullets", [])
            if not isinstance(bullets, list):
                logger.warning(
                    f"Warning: bullets is {type(bullets)}, expected list. Converting.",
                )
                if isinstance(bullets, str):
                    bullets = [b.strip() for b in bullets.splitlines() if b.strip()]
                else:
                    bullets = []

            # Add bullets
            for i, bullet_item in enumerate(bullets):
                # Ensure bullet is a string
                if not isinstance(bullet_item, str):
                    logger.warning(f"Warning: bullet {i} is {type(bullet_item)}, converting to str")
                    bullet_text = str(bullet_item)
                else:
                    bullet_text = bullet_item

                # Create new paragraph for each bullet
                if i == 0 and not has_summary_text:
                    p = text_frame.paragraphs[0]
                else:
                    p = text_frame.add_paragraph()

                # Add bullet text
                clean_text = bullet_text.strip()
                if not clean_text.startswith("•") and not clean_text.startswith("-"):
                    p.text = f"• {clean_text}"
                else:
                    p.text = clean_text

                # Style bullet paragraph
                p.level = 0
                p.font.size = Pt(16)
                p.font.name = font_name
                if font_color:
                    p.font.color.rgb = font_color
                p.space_after = Pt(8)
                p.alignment = PP_ALIGN.LEFT
                p.font.bold = False

        elif layout == "statement":
            statement = s.get("statement", "")
            if not isinstance(statement, str):
                statement = str(statement) if statement else ""
            statement = statement.strip()

            if not statement:
                statement = summary

            if statement:
                p = text_frame.paragraphs[0]
                p.text = f"“{statement}”"
                p.level = 0
                p.font.size = Pt(40)
                p.font.italic = True
                p.font.bold = True
                p.font.name = font_name
                if font_color:
                    p.font.color.rgb = font_color
                p.alignment = PP_ALIGN.CENTER

        elif layout == "big_number":
            big_number = s.get("big_number", "")
            if not isinstance(big_number, str):
                big_number = str(big_number) if big_number else ""
            big_number = big_number.strip()

            big_number_context = s.get("big_number_context", "")
            if not isinstance(big_number_context, str):
                big_number_context = str(big_number_context) if big_number_context else ""
            big_number_context = big_number_context.strip()

            if not big_number:
                big_number = "50%"
                big_number_context = summary or "No context provided"

            p_num = text_frame.paragraphs[0]
            p_num.text = big_number
            p_num.level = 0
            p_num.font.size = Pt(100)
            p_num.font.bold = True
            p_num.font.name = font_name
            if font_color:
                p_num.font.color.rgb = font_color
            p_num.alignment = PP_ALIGN.CENTER
            p_num.space_after = Pt(8)

            if big_number_context:
                p_ctx = text_frame.add_paragraph()
                p_ctx.text = big_number_context
                p_ctx.level = 0
                p_ctx.font.size = Pt(24)
                p_ctx.font.bold = False
                p_ctx.font.name = font_name
                if font_color:
                    p_ctx.font.color.rgb = font_color
                p_ctx.alignment = PP_ALIGN.CENTER

        # Get notes - SAFE EXTRACTION
        notes = s.get("notes", "")
        if not isinstance(notes, str):
            logger.warning(f"Warning: notes is {type(notes)}, converting to str")
            notes = str(notes) if notes else ""
        notes = notes.strip()

        # Add speaker notes if provided
        if notes:
            notes_slide = content_slide.notes_slide
            notes_frame = notes_slide.notes_text_frame
            notes_frame.text = notes

        # Image handling
        image_path = s.get("image_path")
        image_url = s.get("image_url")
        image_prompt = s.get("image_prompt", "")

        if not isinstance(image_prompt, str):
            image_prompt = str(image_prompt) if image_prompt else ""
        image_prompt = image_prompt.strip()

        # Image dimensions and position — right-column layout
        # Start low enough to clear the title bar and give breathing room
        if has_image:
            img_left = Inches(6.8)
            img_width = Inches(2.7)
            img_height = Inches(2.2)
            # Center the image vertically within the content area (1.8 to 6.3)
            img_top = Inches(1.8) + (Inches(4.5) - img_height) / 2

            pic = None

            # Try to fetch image URL first
            if image_url:
                try:
                    logger.info(f"Downloading image from {image_url}...")
                    async with httpx.AsyncClient(timeout=10.0) as client:
                        response = await client.get(image_url)
                    if response.status_code == 200:
                        image_stream = BytesIO(response.content)
                        pic = content_slide.shapes.add_picture(
                            image_stream, img_left, img_top, width=img_width, height=img_height
                        )
                    else:
                        logger.warning(f"Failed to download image: status {response.status_code}")
                except Exception as e:
                    logger.warning(f"Error downloading image: {e}")

            # If no URL or download failed, try local path
            if not pic and image_path and os.path.exists(image_path):
                try:
                    pic = content_slide.shapes.add_picture(
                        image_path, img_left, img_top, width=img_width, height=img_height
                    )
                except Exception as e:
                    logger.warning(f"Image insert failed: {e}")

            # Add alt text if picture was created
            if pic and image_prompt:
                try:
                    if hasattr(pic, "alt_text"):
                        pic.alt_text = image_prompt
                except Exception as e:
                    logger.warning(f"Alt text assignment failed: {e}")

            # Fallback: if no picture was created, create a placeholder box
            if not pic and image_prompt:
                logger.info("Using placeholder shape for image.")
                textbox = content_slide.shapes.add_textbox(img_left, img_top, img_width, img_height)

                textbox_frame = textbox.text_frame
                textbox_frame.text = f"[Image: {image_prompt}]"
                textbox_frame.word_wrap = True
                p = textbox_frame.paragraphs[0]
                p.font.size = Pt(10)
                p.font.italic = True
                p.alignment = PP_ALIGN.CENTER

    # Add References slide if citations exist
    citations = data.get("citations")
    if isinstance(citations, list) and len(citations) > 0:
        logger.info("Adding References slide to PPTX")
        ref_slide = prs.slides.add_slide(blank_layout)

        global_font = data.get("font", "Calibri")
        global_palette = data.get("palette", [])
        font_name = global_font or "Calibri"

        font_color = None
        if global_palette:
            color_hex = global_palette[0]
            try:
                rgb = color_hex.lstrip("#")
                if len(rgb) == 6:
                    font_color = RGBColor(int(rgb[0:2], 16), int(rgb[2:4], 16), int(rgb[4:6], 16))
            except Exception as e:
                logger.warning(f"Color parsing failed for '{color_hex}': {e}")

        # Title box
        title_left = Inches(0.5)
        title_top = Inches(0.5)
        title_width = Inches(9)
        title_height = Inches(0.8)

        title_box = ref_slide.shapes.add_textbox(title_left, title_top, title_width, title_height)
        title_frame = title_box.text_frame
        title_frame.text = "References"
        title_frame.word_wrap = True

        title_para = title_frame.paragraphs[0]
        title_para.font.size = Pt(32)
        title_para.font.bold = True
        title_para.font.name = font_name
        if font_color:
            title_para.font.color.rgb = font_color
        title_para.alignment = PP_ALIGN.LEFT

        # Content box
        content_left = Inches(0.5)
        content_top = Inches(1.5)
        content_width = Inches(9)
        content_height = Inches(5)

        content_box = ref_slide.shapes.add_textbox(content_left, content_top, content_width, content_height)
        text_frame = content_box.text_frame
        text_frame.word_wrap = True

        for i, ref in enumerate(citations):
            if not isinstance(ref, str):
                ref = str(ref)
            ref_text = f"[{i + 1}] {ref.strip()}"
            if i == 0:
                p = text_frame.paragraphs[0]
                p.text = ref_text
            else:
                p = text_frame.add_paragraph()
                p.text = ref_text

            p.level = 0
            p.font.size = Pt(14)
            p.font.name = font_name
            if font_color:
                p.font.color.rgb = font_color
            p.space_after = Pt(12)
            p.alignment = PP_ALIGN.LEFT

    prs.save(output_path)
    logger.info(f"Exported slides to {output_path}")
