"""
PDF Exporter module for the slideia package.
"""

import json
import os
from io import BytesIO

import httpx
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import Paragraph
from slideia.core.logging import get_logger

logger = get_logger(__name__)

# Purple Mint Palette
PRIMARY_COLOR = colors.HexColor("#7C3AED")  # Violet 600
SECONDARY_COLOR = colors.HexColor("#10B981")  # Emerald 500
TEXT_COLOR = colors.HexColor("#1F2937")  # Gray 800
BG_COLOR = colors.HexColor("#FFFFFF")

async def export_deck_to_pdf(input_path: str, output_path: str):
    """
    Export slides from a JSON file to a PDF file.
    """
    if not os.path.exists(input_path):
        logger.error(f"Input file not found: {input_path}")
        raise FileNotFoundError(f"Input file not found: {input_path}")

    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Setup canvas
    c = canvas.Canvas(output_path, pagesize=landscape(A4))
    width, height = landscape(A4)

    # 1. Title Slide
    _draw_title_slide(c, data, width, height)
    c.showPage()

    # 2. Content Slides
    for slide_index, s in enumerate(data.get("slides", [])):
        logger.info(f"Processing PDF slide {slide_index + 1}")
        await _draw_content_slide(c, s, slide_index, width, height)
        c.showPage()

    c.save()
    logger.info(f"Exported PDF to {output_path}")


def _draw_title_slide(c, data, width, height):
    """Draws the title slide."""
    # Background (optional accent)
    c.setFillColor(colors.HexColor("#F9FAFB")) # Light gray bg
    c.rect(0, 0, width, height, fill=1, stroke=0)
    
    # Accent bar at top
    c.setFillColor(PRIMARY_COLOR)
    c.rect(0, height - 10, width, 10, fill=1, stroke=0)

    title = data.get("title", "Untitled Presentation")
    subtitle = data.get("subtitle", "Generated by Slideia")

    # Title
    c.setFont("Helvetica-Bold", 48)
    c.setFillColor(PRIMARY_COLOR)
    c.drawCentredString(width / 2, height / 2 + 20, title)

    # Subtitle
    c.setFont("Helvetica", 24)
    c.setFillColor(TEXT_COLOR)
    c.drawCentredString(width / 2, height / 2 - 40, subtitle)


async def _draw_content_slide(c, s, slide_index, width, height):
    """Draws a single content slide."""
    # Background
    c.setFillColor(BG_COLOR)
    c.rect(0, 0, width, height, fill=1, stroke=0)

    # Title
    title_text = s.get("title", f"Slide {slide_index + 1}")
    c.setFont("Helvetica-Bold", 32)
    c.setFillColor(PRIMARY_COLOR)
    c.drawString(0.5 * inch, height - 0.8 * inch, title_text)

    # Divider line
    c.setStrokeColor(SECONDARY_COLOR)
    c.setLineWidth(2)
    c.line(0.5 * inch, height - 1.0 * inch, width - 0.5 * inch, height - 1.0 * inch)

    # Layout dimensions
    content_width = 6.5 * inch
    image_width = 3 * inch
    
    # Summary & Bullets using Platypus Paragraphs for wrapping
    styles = getSampleStyleSheet()
    
    # Custom Styles
    summary_style = ParagraphStyle(
        'Summary',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=14,
        textColor=TEXT_COLOR,
        leading=18,
        spaceAfter=12
    )
    
    bullet_style = ParagraphStyle(
        'Bullet',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=16,
        textColor=TEXT_COLOR,
        leading=22,
        leftIndent=20,
        bulletIndent=5,
        spaceAfter=8
    )

    current_y = height - 1.5 * inch

    # Draw Summary
    summary = s.get("summary", "")
    if summary:
        p = Paragraph(summary, summary_style)
        w, h = p.wrap(content_width, height)
        p.drawOn(c, 0.5 * inch, current_y - h)
        current_y -= (h + 12)

    # Draw Bullets
    bullets = s.get("bullets", [])
    for bullet_text in bullets:
        # Ensure it's a clean bullet
        clean_text = bullet_text.strip()
        if not (clean_text.startswith("•") or clean_text.startswith("-")):
            clean_text = f"• {clean_text}"
        
        p = Paragraph(clean_text, bullet_style)
        w, h = p.wrap(content_width, height)
        # Check if we run out of space (simplified)
        if current_y - h < 0.5 * inch:
            break
        p.drawOn(c, 0.5 * inch, current_y - h)
        current_y -= (h + 8)

    # Image Handling
    image_url = s.get("image_url")
    image_prompt = s.get("image_prompt", "")
    
    if image_url:
        try:
            logger.info(f"Downloading image for PDF: {image_url}")
            async with httpx.AsyncClient(timeout=10.0) as client:
                response = await client.get(image_url)
            if response.status_code == 200:
                img_data = BytesIO(response.content)
                # Position image on the right
                img_x = width - image_width - 0.5 * inch
                img_y = height - 1.5 * inch - image_width # Keep it squareish or aspect ratio
                
                # Draw image (checking size/aspect ratio would be better but let's start simple)
                c.drawImage(reportlab_image_from_stream(img_data), img_x, img_y, width=image_width, preserveAspectRatio=True, mask='auto')
        except Exception as e:
            logger.warning(f"Failed to add image to PDF: {e}")
            _draw_image_placeholder(c, image_prompt, width, height, image_width)
    elif image_prompt:
        _draw_image_placeholder(c, image_prompt, width, height, image_width)


def _draw_image_placeholder(c, prompt, width, height, img_w):
    """Draws a placeholder for an image."""
    img_x = width - img_w - 0.5 * inch
    img_y = height - 1.5 * inch - img_w
    
    c.setStrokeColor(SECONDARY_COLOR)
    c.setDash(3, 3)
    c.rect(img_x, img_y, img_w, img_w, stroke=1, fill=0)
    
    c.setFont("Helvetica-Oblique", 10)
    c.setFillColor(SECONDARY_COLOR)
    c.drawCentredString(img_x + img_w/2, img_y + img_w/2, f"[Image: {prompt[:30]}...]")
    c.setDash()


def reportlab_image_from_stream(stream):
    """Helper to convert stream to reportlab compatible image."""
    from reportlab.lib.utils import ImageReader
    return ImageReader(stream)
