"""
Exporter module for the slideia package.
"""

import datetime
import json
import os
import sys

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.util import Inches, Pt

from slideia.tools.generate_template import create_minimal_template


def export_slides(input_path: str, output_path: str):
    """
    Export slides from a JSON file (input_path) to a PowerPoint (.pptx) file (output_path), using a
    professional template.

    Accessibility: All images are assigned alt-text (from image_prompt) for screen readers.
    If image insertion fails, a text placeholder is used instead. All logs are sent to stderr to
    avoid interfering with content.

    The input JSON should have the structure:
        {
            "title": str,
            "subtitle": str (optional),
            "slides": [
                {
                    "title": str,
                    "summary": str,
                    "bullets": [str, ...],
                    "image_path": str (optional),
                    "image_prompt": str (optional, for alt text),
                    "notes": str (optional, for speaker notes),
                    "theme": dict (optional, e.g. {"font": "Arial", "color": "#112233"})
                },
                ...
            ]
        }

    Args:
        input_path (str): Path to the input JSON file describing the deck.
        output_path (str): Path to the output .pptx file.
    """

    if not os.path.exists(input_path):
        print(f"[exporter] Input file not found: {input_path}", file=sys.stderr)
        raise FileNotFoundError(f"Input file not found: {input_path}")

    # Use the minimal professional template
    template_path = os.path.join(
        os.path.dirname(__file__), "templates", "base_template.pptx"
    )
    if not os.path.exists(template_path):
        print(
            f"[exporter] Template not found: {template_path}, generating minimal template",
            file=sys.stderr,
        )
        out_path = os.path.join(
            os.path.dirname(__file__), "templates", "base_template.pptx"
        )
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        create_minimal_template(out_path)
        print(f"Template saved to {out_path}", file=sys.stderr)

    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    prs = Presentation(template_path)

    # Remove all slides from the template to avoid duplicates in output
    while len(prs.slides) > 0:
        rId = prs.slides._sldIdLst[0].rId
        prs.part.drop_rel(rId)
        del prs.slides._sldIdLst[0]

    # Title slide (use first layout)
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = data.get("title", "Untitled Presentation")
    if len(slide.placeholders) > 1:
        subtitle = data.get("subtitle", "Generated by slideia exporter")
        slide.placeholders[1].text = subtitle

    # Content slides
    content_layout = prs.slide_layouts[1]

    for slide_index, s in enumerate(data.get("slides", [])):
        content_slide = prs.slides.add_slide(content_layout)

        # Set slide title
        content_slide.shapes.title.text = s.get("title", "Slide")

        # Find the body placeholder
        body_ph = None
        for shape in content_slide.placeholders:
            if shape.placeholder_format.type == 1:  # BODY placeholder
                body_ph = shape
                break

        if body_ph:
            # Clear any existing text
            text_frame = body_ph.text_frame
            text_frame.clear()

            # Set text frame properties
            text_frame.word_wrap = True
            text_frame.margin_left = Inches(0.1)
            text_frame.margin_right = Inches(0.1)
            text_frame.margin_top = Inches(0.1)
            text_frame.margin_bottom = Inches(0.1)

            # Get theme settings
            theme = s.get("theme", {})
            font_name = theme.get("font", "Calibri")

            # Parse color if provided
            font_color = None
            if "color" in theme:
                try:
                    rgb = theme["color"].lstrip("#")
                    font_color = RGBColor(
                        int(rgb[0:2], 16), int(rgb[2:4], 16), int(rgb[4:6], 16)
                    )
                except Exception as e:
                    print(f"[exporter] Color parsing failed: {e}", file=sys.stderr)

            # Add summary if present (as first paragraph, not bullet)
            summary = s.get("summary", "").strip()
            if summary:
                p = text_frame.paragraphs[0]
                p.text = summary
                p.level = 0
                p.font.size = Pt(14)
                p.font.name = font_name
                if font_color:
                    p.font.color.rgb = font_color
                p.space_after = Pt(12)

            # Add bullets
            bullets = s.get("bullets", [])
            for i, bullet_text in enumerate(bullets):
                # Create new paragraph for each bullet
                if i == 0 and not summary:
                    # Use existing first paragraph if no summary
                    p = text_frame.paragraphs[0]
                else:
                    p = text_frame.add_paragraph()

                p.text = bullet_text
                p.level = 0  # First level bullet
                p.font.size = Pt(16)  # Readable bullet size
                p.font.name = font_name
                if font_color:
                    p.font.color.rgb = font_color
                p.space_after = Pt(8)

                # Ensure bullet point is visible
                p.font.bold = False

        # Add speaker notes if provided
        notes = s.get("notes", "").strip()
        if notes:
            notes_slide = content_slide.notes_slide
            text_frame = notes_slide.notes_text_frame
            text_frame.text = notes

        # Insert image if provided, with accessibility and fallback
        image_path = s.get("image_path")
        image_prompt = s.get("image_prompt", "").strip()

        if image_path and os.path.exists(image_path):
            try:
                # Try to find a picture placeholder, else insert at a default position
                pic_placeholder = None
                for shape in content_slide.placeholders:
                    if shape.placeholder_format.type == 18:  # PICTURE
                        pic_placeholder = shape
                        break

                if pic_placeholder:
                    pic = pic_placeholder.insert_picture(image_path)
                else:
                    # Insert at default position (right side)
                    left = Inches(7)
                    top = Inches(2)
                    width = Inches(2.5)
                    pic = content_slide.shapes.add_picture(
                        image_path, left, top, width=width
                    )

                # Set alt text for accessibility
                if pic and image_prompt:
                    try:
                        if hasattr(pic, "alt_text"):
                            pic.alt_text = image_prompt
                    except Exception as e:
                        print(f"[exporter] Alt text assignment failed: {e}", file=sys.stderr)

            except Exception as e:
                print(
                    f"[exporter] Image insert failed: {e}. Using placeholder.",
                    file=sys.stderr,
                )
                if image_prompt:
                    # Add image placeholder as a text box
                    left = Inches(7)
                    top = Inches(2)
                    width = Inches(2.5)
                    height = Inches(2)
                    textbox = content_slide.shapes.add_textbox(left, top, width, height)
                    text_frame = textbox.text_frame
                    text_frame.text = f"[Image: {image_prompt}]"
                    text_frame.word_wrap = True
                    p = text_frame.paragraphs[0]
                    p.font.size = Pt(10)
                    p.font.italic = True
                    p.alignment = PP_ALIGN.CENTER

        elif image_prompt:
            # No image file, but prompt present: add a text placeholder
            left = Inches(7)
            top = Inches(2)
            width = Inches(2.5)
            height = Inches(2)
            textbox = content_slide.shapes.add_textbox(left, top, width, height)
            text_frame = textbox.text_frame
            text_frame.text = f"[Image: {image_prompt}]"
            text_frame.word_wrap = True
            p = text_frame.paragraphs[0]
            p.font.size = Pt(10)
            p.font.italic = True
            p.alignment = PP_ALIGN.CENTER

    prs.save(output_path)
    print(f"[exporter] Exported slides to {output_path}", file=sys.stderr)


def generate_pptx(topic: str, slides: int = 5) -> str:
    """
    Generate a PowerPoint (.pptx) file with a title slide and content slides.

    Args:
        topic (str): The topic/title for the presentation.
        slides (int, optional): Number of content slides to generate. Defaults to 5.

    Returns:
        str: The filename of the generated .pptx deck.
    """

    prs = Presentation()

    # Title slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = topic
    slide.placeholders[1].text = f"Generated by slideia on {datetime.date.today()}"

    # Content slides
    content_layout = prs.slide_layouts[1]
    for i in range(1, slides + 1):
        content_slide = prs.slides.add_slide(content_layout)
        content_slide.shapes.title.text = f"{topic} - Slide {i}"
        content_slide.placeholders[1].text = f"Content for slide {i}."

    filename = f"{topic.replace(' ', '_').lower()}_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.pptx"
    prs.save(filename)
    return filename
