import os
from langgraph.graph import END, StateGraph

from slideia.domain.agent.nodes import (
    classify_intent_node,
    draft_slides_node,
    general_chat_node,
    propose_outline_node,
    refine_deck_node,
    validate_node,
)
from slideia.domain.agent.state import AgentState

# ── Router / Conditional Edge Decision Functions ─────────────────────────


def route_intent(state: AgentState) -> str:
    """Routes to outline generation, refinement, or general chat based on intent."""
    intent = state.get("intent")
    if intent == "CREATE_DECK":
        return "propose_outline"
    elif intent == "EDIT_DECK":
        return "refine_deck"
    else:
        return "general_chat"


def decide_validation(state: AgentState) -> str:
    """Decides whether to retry generation or finish based on validation errors."""
    error = state.get("error")
    retry_count = state.get("retry_count", 0)

    if error and retry_count < 3:
        # Loop back to generate/refine
        intent = state.get("intent")
        if intent == "CREATE_DECK":
            # Increment retry count
            state["retry_count"] = retry_count + 1
            return "draft_slides"
        elif intent == "EDIT_DECK":
            state["retry_count"] = retry_count + 1
            return "refine_deck"

    return END


# ── Graph Compilation ─────────────────────────────────────────────────────


def compile_workflow():
    """Builds and compiles the stateful LangGraph workflow."""
    workflow = StateGraph(AgentState)

    # Add all execution nodes
    workflow.add_node("classify_intent", classify_intent_node)
    workflow.add_node("propose_outline", propose_outline_node)
    workflow.add_node("draft_slides", draft_slides_node)
    workflow.add_node("refine_deck", refine_deck_node)
    workflow.add_node("validate", validate_node)
    workflow.add_node("general_chat", general_chat_node)

    # Set Entry Point
    workflow.set_entry_point("classify_intent")

    # Define Conditional Edge from Intent Classification
    workflow.add_conditional_edges(
        "classify_intent",
        route_intent,
        {
            "propose_outline": "propose_outline",
            "refine_deck": "refine_deck",
            "general_chat": "general_chat",
        },
    )

    # Linear generation flow
    workflow.add_edge("propose_outline", "draft_slides")
    workflow.add_edge("draft_slides", "validate")
    workflow.add_edge("refine_deck", "validate")

    # Define Conditional Edge from Validation
    workflow.add_conditional_edges(
        "validate",
        decide_validation,
        {
            "draft_slides": "draft_slides",
            "refine_deck": "refine_deck",
            END: END,
        },
    )

    # Chat node routes directly to end
    workflow.add_edge("general_chat", END)

    return workflow.compile()


# Compiled Graph instance for external import
graph = compile_workflow()

# ── Self-Documentation Script ──────────────────────────────────────────────

if __name__ == "__main__":
    # Compile graph and write the Mermaid structure representation to file
    mermaid_code = graph.get_graph().draw_mermaid()
    output_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../.."))
    output_path = os.path.join(output_dir, "graph_structure.md")

    with open(output_path, "w") as f:
        f.write("# Slideia AI Agent Graph Structure\n\n")
        f.write("This file is automatically generated by running the `graph.py` module.\n\n")
        f.write("Below is the Mermaid representation of the compiled LangGraph orchestration structure:\n\n")
        f.write("```mermaid\n")
        f.write(mermaid_code)
        f.write("\n```\n")

    print(f"Successfully generated graph structure in: {output_path}")
